### SERVER CONFIG
server:
  port: 8881

### APPLICATION CONFIG
application:
  version: @project.version@


# -Spring.profiles.active=dev

spring:
  profiles:
    active: dev
  ### DB CONFIG
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clinic_db
    username: root
    password: root.123
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### FLYWAY CONFIG
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  ### MAIL CONFIG
  mail:
    host: smtp.gmail.com
    port: 587
    username: clinicapi2023@gmail.com
    password: rupyravopdhebzms
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

### LOGGING CONFIG
logging:
  level:
    root: INFO
  file:
    name: log/clinics_api.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 1GB
      total-size-cap: 10GB

### SPRING DOC CONFIG
springdoc:
  swagger-ui:
    path: swagger-ui
    doc-expansion: none



